boot.o: boot.S multiboot.h x86_desc.h types.h
handler.o: handler.S x86_desc.h types.h
linkage.o: linkage.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h syscall.h terminal_driver.h \
  rtc.h page.h x86_desc.h scheduling.h
i8259.o: i8259.c i8259.h types.h lib.h
IDT.o: IDT.c IDT.h lib.h types.h x86_desc.h keyb.h terminal_driver.h \
  rtc.h handler.h linkage.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  IDT.h keyb.h terminal_driver.h rtc.h page.h filesys.h syscall.h \
  scheduling.h
keyb.o: keyb.c keyb.h types.h terminal_driver.h lib.h i8259.h
lib.o: lib.c lib.h types.h terminal_driver.h
page.o: page.c page.h x86_desc.h types.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
scheduling.o: scheduling.c scheduling.h types.h syscall.h lib.h \
  terminal_driver.h rtc.h filesys.h page.h x86_desc.h i8259.h
syscall.o: syscall.c syscall.h lib.h types.h terminal_driver.h rtc.h \
  filesys.h page.h x86_desc.h scheduling.h
terminal_driver.o: terminal_driver.c terminal_driver.h lib.h types.h \
  keyb.h syscall.h rtc.h filesys.h page.h x86_desc.h scheduling.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h IDT.h rtc.h filesys.h \
  syscall.h terminal_driver.h page.h scheduling.h
